### ISSUE TITLE
The fakeValue parameter is not passed on

### ISSUE THREAD

**Issue by XhstormR** [albinowax/albinowaxUtils#3]
hello, i found a small bug, the fakeValue parameter is not passed on, last parameter of the constructor is still passed null value.
https://github.com/albinowax/albinowaxUtils/blob/main/src/burp/PartialParam.java#L14-L15

**Comment by albinowax** [comment]
Have you encountered a bug that's caused by this? I wrote this a long time ago but I suspect it's deliberate, otherwise the variable would be called 'fake'

**Comment by XhstormR** [comment]
I tried using this class, but found that there was no way to set the value property except through the constructor, but always passed a null value, so I thought it might be a bug. I use `helpers.buildParameter` now.
